import { jsx as _jsx } from "react/jsx-runtime";
import { StrictMode, Suspense } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './scss/global.scss';
import ModalContext from './contexts/ModalContext';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import FullScreenMessage from './components/shared/FullScreenMessage';
import ErrorBoundary from './components/shared/ErrorBoundary';
const queryClient = new QueryClient();
createRoot(document.getElementById('root')).render(_jsx(StrictMode, { children: _jsx(QueryClientProvider, { client: queryClient, children: _jsx(ModalContext, { children: _jsx(ErrorBoundary, { fallbackUI: _jsx(FullScreenMessage, { type: "error" }), children: _jsx(Suspense, { fallback: _jsx(FullScreenMessage, { type: "loading" }), children: _jsx(App, {}) }) }) }) }) }));
